from generator_utils import *
from py_supremica.py_supremica import *


###
# Setup
###

fileName = "gen/anim/Drone2Animate"
moduleComment = "This is an autogenerated termite supervisor, current version - 3"

isMulti = True # Defines if supervisors work with external events
heightMap = [[4,0,1],
             [0,0,0],
             [3,0,2]]  

###
# Initialization
##

# HeightMap shape
M = len(heightMap)
N = len(heightMap[0])

border = []
for i in range(1,M+1):
    for j in range(1,N+1):
        if i == 1 or i == M or j == 1 or j == N:
            border.append((i,j))

inTiles = border
outTiles = border

enc = GenEnc(M,N)

# Init Module and add comment
mod = Module("Supervisor")
mod.comment = moduleComment

# Init alphabet
ga = Alphabet()
mod.alphabet = ga

# Define base events
ga.newEvent("getBrick")
ga.newEvent("l")
ga.newEvent("r")
ga.newEvent("u")
ga.newEvent("d")

ga.newEvent("nw")
ga.newEvent("sw")
ga.newEvent("ne")
ga.newEvent("se")

for (i,j) in inTiles:
    ga.newEvent(enc.inEnc(i,j))

for (i,j) in inTiles:
    ga.newEvent(enc.outEnc(i,j))

# Position variables 
mod.addVariable("x","x==0",[0,N+1])
mod.addVariable("y","y==0",[0,M+1])

# heightmap shape constants (#observe)
mod.addConstant("M",M)
mod.addConstant("N",N)

# Initialize height variables, height constants and placing events
placing_events = []
for i in range(1,M+1):
    for j in range(1,N+1):

        # Check if there is need for creation
        if(heightMap[i-1][j-1]>0):

            # Set addTile Events
            event_name = enc.placingEnc(i,j)
            placing_events.append(event_name)
            ga.newEvent(event_name)
            if isMulti:
                ga.newEvent(enc.placingEnc(i,j) + enc.altEnc(), kind="CONTROLLABLE")

            # Set height constants 
            constName = "H"+enc.coordEnc(i,j)
            mod.addConstant(constName, heightMap[i-1][j-1])
        
        # Set height variables
        mod.addVariable(enc.heightEnc(i,j),
                        enc.heightEnc(i,j) + "==0",
                        [0,heightMap[i-1][j-1]+1])


###
# Automata
###

### GR Automaton or G1 ###

gr = Automaton()

# Create states
gr.addState("OUT",initial=True, accepting=True)
gr.addState("IN")

# Add getBrick event
gr.addEdge("OUT","OUT",ga()["getBrick"])

# Add enter grid events
for idx in range(len(inTiles)):
    tile = inTiles[idx]
    i = tile[0]
    j = tile[1]

    gr.addEdge("OUT","IN",ga()[enc.inEnc(i,j)])
    gr.setEdgeActions("OUT", "IN", "y="+str(i)+";x="+str(j),idx)


# Add exit grid events
for idx in range(len(outTiles)):
    tile = outTiles[idx]
    i = tile[0]
    j = tile[1]

    gr.addEdge("IN","OUT",ga()[enc.outEnc(i,j)])
    gr.setEdgeActions("IN", "OUT", "x=0;y=0",idx)
    gr.setEdgeGuard("IN", "OUT", "y=="+ str(i) + "&x=="+str(j),idx)
        

# Add movement in grid events
gr.addEdge("IN","IN",ga()["l"])
gr.setEdgeGuard("IN","IN","x>1")
gr.setEdgeActions("IN","IN","x-=1")

gr.addTransition("IN","IN",ga()["r"])
gr.setEdgeGuard("IN","IN","x<"+str(N),1)
gr.setEdgeActions("IN","IN","x+=1",1)

gr.addTransition("IN","IN",ga()["d"])
gr.setEdgeGuard("IN","IN","y<"+str(M),2)
gr.setEdgeActions("IN","IN","y+=1",2)

gr.addTransition("IN","IN",ga()["u"])
gr.setEdgeGuard("IN","IN","y>1",3)
gr.setEdgeActions("IN","IN","y-=1",3)


gr.addEdge("IN","IN",ga()["ne"])
gr.setEdgeGuard("IN","IN","x<"+str(N)+"&y>1",4)
gr.setEdgeActions("IN","IN","x+=1;y-=1",4)

gr.addEdge("IN","IN",ga()["nw"])
gr.setEdgeGuard("IN","IN","x>1&y>1",5)
gr.setEdgeActions("IN","IN","x-=1;y-=1",5)

gr.addEdge("IN","IN",ga()["sw"])
gr.setEdgeGuard("IN","IN","x>1&"+"y<"+str(M),6)
gr.setEdgeActions("IN","IN","x-=1;y+=1",6)

gr.addEdge("IN","IN",ga()["se"])
gr.setEdgeGuard("IN","IN","x<"+str(N)+"&"+"y<"+str(M),7)
gr.setEdgeActions("IN","IN","x+=1;y+=1",7)

mod.automata["GR"] = gr

### GB Automaton or G2 ###

g_b = Automaton()

# Create states
g_b.addState("S0", initial=True,accepting=True)
g_b.addState("S1",accepting=True)

g_b.addEdge("S0","S1", ga()["getBrick"])
g_b.addEdge("S1","S0", [ga()[e] for e in placing_events] )

mod.automata["G_B"] = g_b


###
# Variable Automata
###

### Gadd_ix Automaton or G3 ###

for i in range(1,M+1):
    if(sum(heightMap[i-1]) > 0):
        ### Gadd_ix Automaton or G3 ###
        gadd_ix = Automaton()
        gadd_ix.addState("L1", initial=True, accepting=True)

        ### Gadd_ix Automaton (for external events) or G3 ###
        if isMulti:
            gadd_ix_r2 = Automaton()
            gadd_ix_r2.addState("L1", initial=True, accepting=True)

        count = 0
        for j in range(1,N+1):
            if heightMap[i-1][j-1] > 0:

                ### Populate G3's ###
                gadd_ix.addEdge("L1","L1",ga()[enc.placingEnc(i,j)])
                gadd_ix.setEdgeActions("L1","L1",enc.heightEnc(i,j)+"+=1",count)

                guard = "(x=="+str(j)+" & y=="+str(i)+")"

                gadd_ix.setEdgeGuard("L1","L1",guard,count)

                if isMulti:
                    gadd_ix_r2.addEdge("L1","L1",ga()[enc.placingEnc(i,j)+enc.altEnc()])
                    gadd_ix_r2.setEdgeActions("L1","L1",enc.heightEnc(i,j)+"+=1",count)
            

                ### E_Uij Automaton or G7 ###
                neighbors = enc.getNeighbors(i,j,True)

                if neighbors:
                    e_uij = Automaton(kind="SPEC")
                    e_uij.addState("S0",initial=True, accepting=True)
                    e_uij.addEdge("S0","S0",ga()[enc.placingEnc(i,j)])
                    e_uij.addEventToEdge("S0","S0",ga()[enc.placingEnc(i,j)+enc.altEnc()])
                    guard = ""
                    for n in neighbors:
                        guard += "("+enc.heightEnc(n[0],n[1])+" <= "+enc.heightEnc(i,j)+")&"
                    e_uij.setEdgeGuard("S0","S0",guard)

                    mod.automata["E_U"+enc.coordEnc(i,j)] = e_uij


                ### E_Hij Automaton or G8 ###
                e_hij = Automaton(kind="SPEC")
                e_hij.addState("B0", initial=True)
                e_hij.addState("B1", accepting=True)

                e_hij.addEdge("B0","B0",ga()[enc.placingEnc(i,j)])
                e_hij.addEventToEdge("B0","B0", ga()[enc.placingEnc(i,j)+"_r2"])
                e_hij.setEdgeGuard("B0","B0",enc.heightEnc(i,j)+"<"+"H"+enc.coordEnc(i,j)+"-1")

                e_hij.addEdge("B0","B1",ga()[enc.placingEnc(i,j)])
                e_hij.addEventToEdge("B0","B1", ga()[enc.placingEnc(i,j)+"_r2"])
                e_hij.setEdgeGuard("B0","B1",enc.heightEnc(i,j)+"=="+"H"+enc.coordEnc(i,j)+"-1")

                mod.automata["E_H"+enc.coordEnc(i,j)] = e_hij

                count += 1


         ### Finish G3's ###
        mod.automata["GAdd_"+str(i)+"X"] = gadd_ix
        if isMulti:
            mod.automata["GAdd_"+str(i)+"X"+enc.altEnc()] = gadd_ix_r2





        

#  Generate
mod.toWMOD(fileName)